version: '3.8'

services:
  db:
    image: 3844320/todo_one-db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env  # Добавлено, чтобы загрузить переменные окружения
    deploy:
      resources:
        limits:
          memory: 256M  # Лимит памяти для контейнера db
          cpus: '0.5'    # Лимит на использование процессора (50% одного ядра)

  app:
    image: 3844320/todo_one-app:latest
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env  # Добавлено, чтобы загрузить переменные окружения
    deploy:
      resources:
        limits:
          memory: 128M  # Лимит памяти для контейнера app
          cpus: '0.5'    # Лимит на использование процессора (50% одного ядра)

volumes:
  db_data:
