services:
  db:
    image: 3844320/todo_one-db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: 3844320/todo_one-app:latest
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:
